### ISSUE TITLE
Tool is stuck at step 2 (kmer.sh script)

### ISSUE THREAD

**Issue by rolibudhwar** [xiekunwhy/kmerDedup#2]
Hi
I am running KmerDedup on my highly duplicated assembly (created using hifiasm) as the many sample were pooled together (one organism). KmerDedup has successfully generated the shell script. Step01 i.e indexing step was done quite fast. But the tool is stuck at step02 (kmer.sh) for almost 16hrs. No error msg as such..please let us know what could be the probable cause.

Thanks,

**Comment by xiekunwhy** [comment]
Hi,

Are you stuck at **jellyfish count** step?
Increasing thread number (jellyfish count -t option, or thread_large in config file) may be speed up k-mer counting step.
By the way, please don't use long noise reads to get k-mers.

Best,
Kun
