### ISSUE TITLE
All contigs are categorized as "lowcov"

### ISSUE THREAD

**Issue by sivico26** [xiekunwhy/kmerDedup#3]
Hello there,

Thanks for making this interesting tool. I struggled to follow the steps to arrive at the final script but I managed. 

The problem now is that when I run `kmerDedup.pl`, using the follwing parameters:

```
kmerDedup.pl -k "$pre" -mpr 0.3 -mcv 30 -kmer 21 -o kmerdedup03 -f "$asm" -bam mapped.srt.bam -cov "$pre.cov.stat" -s samtools
```

I am getting that all the contigs are being tagged as "lowcov" and thus no separation is being done (all contigs are "kept"). My input mapped kmers are named sorted (they are supposed to be named sorted, right?).

My `*.all.xls` file looks like this:

```raw
#contig length  mapKmer coverage        compareTo       shareRatio      shareCov        fate
ptg000002l      61577133        27400409        0.9938242       null    0       0       lowcov
ptg000337l      30384560        16578706        0.9976798       ptg000002l      0.268738        0.002681        lowcov
ptg000420l      29655932        11209095        0.9897289       ptg000002l      0.335624        0.003322        lowcov
ptg000011l      28285118        17060955        0.9969835       ptg000002l      0.226277        0.002256        lowcov
ptg000008l      27275522        11494363        0.9857126       ptg000002l      0.324252        0.003196        lowcov
ptg000433l      26015101        14076061        0.9982314       ptg000002l      0.288988        0.002885        lowcov
ptg000886l      25647613        15416937        0.9970328       ptg000002l      0.254508        0.002538        lowcov
ptg000068l      23947151        13638911        0.9975476       ptg000002l      0.284388        0.002837        lowcov
ptg000132l      22817751        13263947        0.9974059       ptg000002l      0.285932        0.002852        lowcov
ptg000502l      20875537        13203300        0.9971509       ptg000002l      0.268904        0.002681        lowcov
ptg000080l      20581962        12970194        0.9969487       ptg000002l      0.234640        0.002339        lowcov
ptg000209l      20545502        12293141        0.9968529       ptg000002l      0.282731        0.002818        lowcov
ptg000218l      20537489        13046480        0.9977248       ptg000002l      0.266306        0.002657        lowcov
ptg000746l      20305448        13340473        0.9968930       ptg000002l      0.245526        0.002448        lowcov
ptg000109l      19811236        11599653        0.9974699       ptg000002l      0.290844        0.002901        lowcov
ptg000297l      19618842        10936476        0.9977196       ptg000002l      0.319403        0.003187        lowcov
ptg000060l      19493613        12446209        0.9974508       ptg000002l      0.263643        0.002630        lowcov
```

And for completeness, my input the tail of my `*.cov.stat` file looks like this:

```
ptg001868l      40242   40242   844493  1.0000000       20.9853878
ptg001869l      26345   20032   391566  0.7603720       14.8630104
ptg001870l      25781   21509   438206  0.8342966       16.9972839
ptg001871l      19063   19052   399167  0.9994230       20.9394112
ptg001872l      29323   29323   606669  1.0000000       20.6891861
ptg001873l      29401   29401   617000  1.0000000       20.9857140
ptg001874l      30068   30068   631008  1.0000000       20.9860325
ptg001875l      8869    8869    185786  1.0000000       20.9479084
ptg001876l      26550   26550   557129  1.0000000       20.9841805
#Genome 4004542021      3984214213      82407330205     0.994924        20.5785
```

Can you tell me what I am doing wrong? Or what could be the issue?

Thank you in advance
Sivico

**Comment by xiekunwhy** [comment]
Would you please send the *.dump.hash file and *.cov.stat file to xiekunwhy@foxmail.com, I need to look into it to find the problem.

**Comment by sivico26** [comment]
Thank you for the fast reply @xiekunwhy. I sent the data already. Let me know if I can be of further help.

**Comment by xiekunwhy** [comment]
Which version of BamDeal (https://github.com/BGI-shenzhen/BamDeal) you have used, the **Coverage%** column (the 5th column) in *.cov.stat file range from 0 to 100, not 0 to 1, please use latest version of BamDeal or multiply 100 manually.

**Comment by xiekunwhy** [comment]
By the way use -dum *.dump.hash instead of -bam *.bam to rerun can speed up running.

**Comment by sivico26** [comment]
Sorry for the late reply @xiekunwhy. Thanks for spotting the problem. Indeed correcting the formatting from proportions to % fixed the issue. 

I did not use `BamDeal` because it was quite a cumbersome dependency to install in my cluster, so I replaced the functionality with a combination of `bedtools` and `awk`. 

I already made an effort to make a script to run the whole process making it more user-friendly, and it could be useful for other users. Would you be open to a PR for this purpose? 

Otherwise, thank you for developing `Kmerdedup`, I really like the concept and I would like to see people being more aware of it.

**Comment by xiekunwhy** [comment]
You can paste bedtools or others (like pandepth) command line here, which may give other another option.
